<?php

declare(strict_types=1);

namespace Webconsulting\AstryxTypo3\Tests\Unit;

use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;

/**
 * The atomic-design contract, enforced.
 *
 * A design system that is only a convention decays: the first template that
 * writes `class="astryx-button primary"` because it is quicker costs nothing,
 * and the two hundredth makes the system unmaintainable. Everything the 2.0
 * refactor established is asserted here instead of documented and hoped for.
 *
 * What these rules read is the filesystem. Three of them used to compare
 * Build/Data/component-contract.json against the components it described, which
 * only ever caught the file being out of date with the directory it was written
 * from; both JSON files are generated by
 * Build/Scripts/sync-component-contract.mjs now, and `npm run build` plus CI's
 * `git diff --exit-code` is what keeps them current.
 */
final class AtomicDesignConformanceTest extends TestCase
{
    private const EXT_ROOT = __DIR__ . '/../..';

    private const NAMESPACE_URI = 'http://typo3.org/ns/Webconsulting/AstryxTypo3/Components/ComponentCollection';

    /**
     * Classes that may still appear in a template, and why.
     *
     * Each entry must still match something. An allowlist whose entries no
     * longer occur is an allowlist nobody has read in a year, and it will
     * eventually excuse something it was never meant to.
     */
    private const CLASS_ALLOWLIST = [
        'astryx-prose' => 'Styles the descendants of editor rich text — markup no template ever sees, '
            . 'so it is a stylesheet hook rather than a component with a call site.',
    ];

    /**
     * Class prefixes a template may write, and the one exception.
     *
     * `astryx-` is the design system and `g-` is an element's own namespace.
     * Anything else is a class with no owner: nobody can tell from its name
     * which stylesheet is allowed to style it, and the 2.0 refactor found four
     * of them that no stylesheet did any more.
     */
    private const CLASS_PREFIXES = ['astryx-', 'g-'];

    /**
     * Foreign classes a template may write, and whose contract they are.
     *
     * EXT:solr binds its own behaviour to these names: they are that
     * extension's API, not ours, and renaming one silently turns off faceting
     * or the AJAX result update.
     */
    private const FOREIGN_CLASSES = [
        'tx_solr' => 'EXT:solr scopes its own JavaScript to this wrapper.',
        'tx-solr-facet-hidden' => 'EXT:solr hides the options past the limit with this class.',
        'tx-solr-facet-show-all' => 'EXT:solr binds the “show all options” toggle to this class.',
        'solr-ajaxified' => 'EXT:solr replaces the result list in place for links carrying it.',
        'facet' => 'EXT:solr’s facet JavaScript selects on it.',
        'facet-option' => 'EXT:solr’s facet JavaScript selects on it.',
        'facet-option-list' => 'EXT:solr’s facet JavaScript selects on it.',
        'facet-type-options' => 'EXT:solr’s facet JavaScript selects on it.',
        'fluidfacet' => 'EXT:solr’s facet JavaScript selects on it.',
        'remove-facet-option' => 'EXT:solr’s facet JavaScript selects on it.',
    ];

    /**
     * Which layer may use which. Brad Frost's direction, made one-way.
     *
     * @var array<string, list<string>>
     */
    private const LAYER_MAY_USE = [
        'Layout' => [],
        'Atom' => [],
        'Molecule' => ['Atom', 'Layout'],
        'Organism' => ['Atom', 'Layout', 'Molecule', 'Organism'],
    ];

    /**
     * Templates that render no h1, and why.
     *
     * The element-library preview is not a page: it renders one content
     * element on an otherwise empty document so the picker can photograph it,
     * and a heading above that element would be in the picture.
     */
    private const WITHOUT_A_PAGE_HEADING = [
        'ElementPreview' => 'The element library photographs one element; a heading would be in the picture.',
    ];

    /** @var array<string, mixed> */
    private static array $map;

    public static function setUpBeforeClass(): void
    {
        self::$map = self::readJson('Build/Data/component-map.json');
    }

    // ------------------------------------------------------------- fixtures

    /** @return array<string, mixed> */
    private static function readJson(string $relative): array
    {
        $path = self::EXT_ROOT . '/' . $relative;
        self::assertFileExists($path);

        return json_decode((string)file_get_contents($path), true, 512, JSON_THROW_ON_ERROR);
    }

    /** @return list<string> every template a content element, page or search result renders through */
    private static function templateFiles(): array
    {
        $files = glob(self::EXT_ROOT . '/ContentBlocks/ContentElements/*/templates/frontend.html') ?: [];
        foreach (['Templates/Pages', 'Templates/Partials/Pages', 'Templates/Layouts/Pages'] as $dir) {
            $files = [...$files, ...(glob(self::EXT_ROOT . '/Resources/Private/' . $dir . '/*.html') ?: [])];
        }
        $solr = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator(self::EXT_ROOT . '/Resources/Private/Solr', \FilesystemIterator::SKIP_DOTS),
        );
        foreach ($solr as $file) {
            if ($file->getExtension() === 'html') {
                $files[] = $file->getPathname();
            }
        }
        sort($files);

        return $files;
    }

    /** @return list<string> */
    private static function componentFiles(): array
    {
        return glob(self::EXT_ROOT . '/Resources/Private/Components/*/*/*.fluid.html') ?: [];
    }

    private static function relative(string $path): string
    {
        $root = realpath(self::EXT_ROOT);

        return $root === false ? $path : str_replace($root . '/', '', (string)realpath($path));
    }

    /**
     * Split a class attribute into tokens, keeping `{…}` expressions whole.
     *
     * @return list<string>
     */
    private static function classTokens(string $value): array
    {
        $tokens = [];
        $current = '';
        $depth = 0;
        foreach (str_split($value) as $char) {
            if ($char === '{') {
                $depth++;
            } elseif ($char === '}') {
                $depth = max(0, $depth - 1);
            }
            if ($depth === 0 && trim($char) === '') {
                if ($current !== '') {
                    $tokens[] = $current;
                    $current = '';
                }
                continue;
            }
            $current .= $char;
        }
        if ($current !== '') {
            $tokens[] = $current;
        }

        /*
         * A class an inline f:if chooses is still a class. `{f:if(condition: …,
         * then: 'asc', else: 'desc')}` is one token by the rule above, and
         * `asc` and `desc` were hiding inside it — so every single-quoted
         * literal in an expression is split out and judged as well. A literal
         * that is not a class name (a label, a link target) is harmless: it is
         * checked against the same prefixes and a sentence is not a class.
         */
        foreach ($tokens as $token) {
            if (!str_starts_with($token, '{') && !str_contains($token, '{')) {
                continue;
            }
            if (!preg_match_all("#'([^']*)'#", $token, $literals)) {
                continue;
            }
            foreach ($literals[1] as $literal) {
                foreach (preg_split('#\s+#', trim($literal)) ?: [] as $word) {
                    if ($word !== '' && preg_match('#^[a-zA-Z][a-zA-Z0-9_-]*$#', $word) === 1) {
                        $tokens[] = $word;
                    }
                }
            }
        }

        return $tokens;
    }

    /**
     * Every class attribute in a file, as [value, line].
     *
     * `f:variable` bodies count as class attributes too. Two elements used to
     * assemble `astryx-grid cols-3` and `astryx-item align-start` into a
     * variable and interpolate the result, which is the same thing as writing
     * the classes — and it slipped past this scan for a year, long enough for
     * every modifier in those strings to stop matching anything.
     *
     * @return list<array{0: string, 1: string}>
     */
    private static function classAttributes(string $source): array
    {
        $source = (string)preg_replace('#<f:comment>.*?</f:comment>#s', '', $source);

        $found = [];
        $patterns = [
            '#class="([^"]*)"#s',
            '#<f:variable\s+name="[^"]*(?:[Cc]lass|Surface)"\s*>(.*?)</f:variable>#s',
        ];
        foreach ($patterns as $pattern) {
            if (!preg_match_all($pattern, $source, $matches, PREG_OFFSET_CAPTURE)) {
                continue;
            }
            foreach ($matches[1] as $match) {
                $line = substr_count(substr($source, 0, $match[1]), "\n") + 1;
                // A variable body holds ViewHelper tags around the class names;
                // the names are what is being looked for, so the tags go.
                $found[] = [trim((string)preg_replace('#<[^>]*>#', ' ', $match[0])), (string)$line];
            }
        }

        return $found;
    }

    // -------------------------------------------------------------- the rules

    #[Test]
    public function noTemplateAppliesAnAstryxClassDirectly(): void
    {
        $offences = [];
        $allowlistHits = array_fill_keys(array_keys(self::CLASS_ALLOWLIST), 0);

        foreach (self::templateFiles() as $file) {
            foreach (self::classAttributes((string)file_get_contents($file)) as [$value, $line]) {
                foreach (self::classTokens($value) as $token) {
                    if (!str_starts_with($token, 'astryx-')) {
                        continue;
                    }
                    if (array_key_exists($token, self::CLASS_ALLOWLIST)) {
                        $allowlistHits[$token]++;
                        continue;
                    }
                    $offences[] = sprintf('%s:%s  %s', self::relative($file), $line, $token);
                }
            }
        }

        self::assertSame(
            [],
            $offences,
            "A template applied an Astryx class directly instead of composing a component.\n"
            . implode("\n", array_slice($offences, 0, 40))
            . (count($offences) > 40 ? sprintf("\n… and %d more", count($offences) - 40) : ''),
        );

        foreach ($allowlistHits as $class => $hits) {
            self::assertGreaterThan(
                0,
                $hits,
                sprintf(
                    'The class allowlist still excuses "%s" ("%s") but no template uses it any more. '
                    . 'Remove the entry: an allowlist nobody reads eventually excuses something it was '
                    . 'never meant to.',
                    $class,
                    self::CLASS_ALLOWLIST[$class],
                ),
            );
        }
    }

    #[Test]
    public function noTemplateWritesAClassWithNoOwner(): void
    {
        $foreignHits = array_fill_keys(array_keys(self::FOREIGN_CLASSES), 0);

        $offences = [];
        foreach ([...self::templateFiles(), ...self::componentFiles()] as $file) {
            foreach (self::classAttributes((string)file_get_contents($file)) as [$value, $line]) {
                foreach (self::classTokens($value) as $token) {
                    // An interpolated value is judged where it is assigned.
                    if (str_starts_with($token, '{')) {
                        continue;
                    }
                    $token = (string)preg_replace('#\{.*$#s', '', $token);
                    if ($token === '') {
                        continue;
                    }
                    foreach (self::CLASS_PREFIXES as $prefix) {
                        if (str_starts_with($token, $prefix)) {
                            continue 2;
                        }
                    }
                    if (array_key_exists($token, self::FOREIGN_CLASSES)) {
                        $foreignHits[$token]++;
                        continue;
                    }
                    $offences[] = sprintf('%s:%s  %s', self::relative($file), $line, $token);
                }
            }
        }

        self::assertSame(
            [],
            array_values(array_unique($offences)),
            "A template wrote a class that belongs to no namespace. `astryx-` is the design\n"
            . "system and `g-` is an element's own; a bare word is a class nobody can tell the\n"
            . "owner of, and every one the 2.0 refactor found had stopped matching a stylesheet.\n"
            . "Modifiers are data attributes: data-density=\"compact\", not class=\"compact\".\n"
            . implode("\n", array_slice(array_unique($offences), 0, 40)),
        );

        foreach ($foreignHits as $class => $hits) {
            self::assertGreaterThan(
                0,
                $hits,
                sprintf(
                    'FOREIGN_CLASSES still excuses "%s" ("%s") but no template writes it any more.',
                    $class,
                    self::FOREIGN_CLASSES[$class],
                ),
            );
        }
    }

    #[Test]
    public function everyContentElementRootsInASection(): void
    {
        $offences = [];
        foreach (glob(self::EXT_ROOT . '/ContentBlocks/ContentElements/*/templates/frontend.html') ?: [] as $file) {
            $source = (string)file_get_contents($file);

            /*
             * Comments first. Three elements explain in prose why they do NOT
             * use a <time>, an <address> or an <article>, and a scan that reads
             * the comment finds the tag name in the explanation.
             */
            $source = (string)preg_replace('#<f:comment>.*?</f:comment>#s', '', $source);

            // The first tag that is neither a ViewHelper nor the <html> wrapper
            // is the element's own root. A ViewHelper before it is setting up a
            // variable, not opening the markup.
            if (!preg_match_all('#<((?:[a-z]+:)?[a-zA-Z][a-zA-Z0-9.]*)#', $source, $matches)) {
                $offences[] = self::relative($file) . '  (no tag at all)';
                continue;
            }

            $root = null;
            foreach ($matches[1] as $tag) {
                if ($tag === 'html') {
                    continue;
                }
                if (str_contains($tag, ':') && !str_starts_with($tag, 'a:')) {
                    continue;
                }
                $root = $tag;
                break;
            }

            if ($root !== 'a:layout.section') {
                $offences[] = sprintf('%s  roots in <%s>', self::relative($file), $root ?? 'nothing');
            }
        }

        self::assertSame(
            [],
            $offences,
            "Every content element roots in a:layout.section — that is what gives the catalog one\n"
            . "vertical rhythm and one surface vocabulary across 250 elements.\n"
            . implode("\n", $offences),
        );
    }

    #[Test]
    public function theLayerGraphIsOneWay(): void
    {
        $offences = [];
        foreach (self::componentFiles() as $file) {
            $layer = basename(dirname(dirname($file)));
            $allowed = self::LAYER_MAY_USE[$layer] ?? null;
            self::assertNotNull($allowed, sprintf('Unknown layer "%s" at %s', $layer, self::relative($file)));

            $source = (string)file_get_contents($file);
            if (!preg_match_all('#<a:([a-z]+)\.([a-zA-Z][a-zA-Z0-9]*)#', $source, $matches, PREG_SET_ORDER)) {
                continue;
            }

            foreach ($matches as $match) {
                $usedLayer = ucfirst($match[1]);
                if ($usedLayer === $layer && $layer !== 'Organism') {
                    // A layer using itself is how Card reaches CardTitle. Allowed
                    // within a layer, never across one upwards.
                    continue;
                }
                if (!in_array($usedLayer, $allowed, true) && $usedLayer !== $layer) {
                    $offences[] = sprintf(
                        '%s (%s) uses a:%s.%s (%s)',
                        self::relative($file),
                        $layer,
                        $match[1],
                        $match[2],
                        $usedLayer,
                    );
                }
            }
        }

        self::assertSame(
            [],
            $offences,
            "The layer graph points one way: Atom and Layout import nothing, Molecule may use\n"
            . "Atom and Layout, only Organism may use everything.\n"
            . implode("\n", $offences),
        );
    }

    #[Test]
    public function everyComponentNamedInATemplateExistsOnDisk(): void
    {
        $onDisk = [];
        foreach (self::componentFiles() as $file) {
            $layer = basename(dirname(dirname($file)));
            $name = basename($file, '.fluid.html');
            $onDisk[lcfirst($layer) . '.' . lcfirst($name)] = true;
        }

        $offences = [];
        foreach ([...self::templateFiles(), ...self::componentFiles()] as $file) {
            $source = (string)file_get_contents($file);
            if (!preg_match_all('#</?a:([a-zA-Z][a-zA-Z0-9.]*)#', $source, $matches)) {
                continue;
            }
            foreach (array_unique($matches[1]) as $used) {
                if (!isset($onDisk[$used])) {
                    $offences[] = sprintf('%s  <a:%s>', self::relative($file), $used);
                }
            }
        }

        self::assertSame(
            [],
            array_values(array_unique($offences)),
            "A template names a component that is not in Resources/Private/Components/.\n"
            . implode("\n", array_unique($offences)),
        );
    }

    #[Test]
    public function everyComponentDeclaresTheArgumentsItsCallSitesPass(): void
    {
        $declared = [];
        foreach (self::componentFiles() as $file) {
            $layer = basename(dirname(dirname($file)));
            $name = basename($file, '.fluid.html');
            $key = lcfirst($layer) . '.' . lcfirst($name);

            $source = (string)file_get_contents($file);
            preg_match_all('#<f:argument\s[^>]*name="([^"]+)"#', $source, $matches);
            $declared[$key] = array_flip($matches[1]);
        }

        $offences = [];
        foreach ([...self::templateFiles(), ...self::componentFiles()] as $file) {
            $source = (string)file_get_contents($file);
            if (!preg_match_all('#<a:([a-zA-Z][a-zA-Z0-9.]*)((?:\s[^>]*?)?)/?>#s', $source, $matches, PREG_SET_ORDER)) {
                continue;
            }

            foreach ($matches as $match) {
                $key = $match[1];
                if (!isset($declared[$key])) {
                    continue; // reported by everyComponentNamedInATemplateExistsOnDisk
                }
                preg_match_all('#([a-zA-Z_][-a-zA-Z0-9_]*)\s*=\s*"#', $match[2], $attributes);
                foreach ($attributes[1] as $attribute) {
                    if (isset($declared[$key][$attribute])) {
                        continue;
                    }
                    $offences[] = sprintf('<a:%s %s="…">  in %s', $key, $attribute, self::relative($file));
                }
            }
        }

        $offences = array_values(array_unique($offences));
        self::assertSame(
            [],
            $offences,
            "A call site passes an attribute the component never declares with <f:argument>.\n"
            . "Fluid would silently drop it, so the markup would be right in the template and\n"
            . "wrong on the page.\n"
            . implode("\n", array_slice($offences, 0, 40))
            . (count($offences) > 40 ? sprintf("\n… and %d more", count($offences) - 40) : ''),
        );
    }

    #[Test]
    public function everyMatrixAstryxReferenceIsMapped(): void
    {
        $mapped = self::$map['components'];
        $inventory = [];
        foreach (self::readJson('Build/astryx/components.json')['components'] as $component) {
            $inventory[$component['component']] = true;
        }

        $unmapped = [];
        $unknownUpstream = [];
        foreach (glob(self::EXT_ROOT . '/Build/Data/matrix/*.json') ?: [] as $file) {
            $rows = json_decode((string)file_get_contents($file), true, 512, JSON_THROW_ON_ERROR);
            $rows = $rows['elements'] ?? $rows;
            foreach ($rows as $row) {
                foreach ($row['astryx'] ?? [] as $name) {
                    if (!isset($mapped[$name])) {
                        $unmapped[] = sprintf('%s (row %s)', $name, $row['id'] ?? '?');
                    }
                    if (!isset($inventory[$name])) {
                        $unknownUpstream[] = sprintf('%s (row %s)', $name, $row['id'] ?? '?');
                    }
                }
            }
        }

        self::assertSame(
            [],
            array_values(array_unique($unmapped)),
            "A matrix row names an Astryx component that Build/Data/component-map.json does not map.\n"
            . implode("\n", array_unique($unmapped)),
        );
        self::assertSame(
            [],
            array_values(array_unique($unknownUpstream)),
            'A matrix row names an Astryx component that is not in the vendored inventory for '
            . self::readJson('Build/astryx/components.json')['release'] . ".\n"
            . implode("\n", array_unique($unknownUpstream)),
        );
    }

    #[Test]
    public function everyTemplateUsingComponentsDeclaresTheNamespace(): void
    {
        $offences = [];
        foreach (self::templateFiles() as $file) {
            $source = (string)file_get_contents($file);
            if (!str_contains($source, '<a:')) {
                continue;
            }
            if (!str_contains($source, self::NAMESPACE_URI)) {
                $offences[] = self::relative($file);
            }
        }

        self::assertSame(
            [],
            $offences,
            "A template composes a: components without declaring the namespace. Fluid renders the\n"
            . "tag as literal text rather than failing, so this is invisible until someone looks at\n"
            . "the page source.\n"
            . implode("\n", $offences),
        );
    }

    /**
     * No stylesheet selects a modifier as a class — ours or an element's.
     *
     * This used to compare against a written-down list of every modifier, which
     * meant a component nobody had listed could quietly keep its 1.x selectors:
     * a hundred and fifty of them did, across the components that had CSS but no
     * Fluid component yet. The shape is what is wrong, so the shape is what is
     * matched. `.astryx-card.astryx-clickable-card` is two components on one
     * element, which is a different thing and stays allowed.
     */
    #[Test]
    public function noStylesheetSelectsAModifierAsAClass(): void
    {
        $sheets = glob(self::EXT_ROOT . '/Resources/Private/Css/components/*.css') ?: [];
        $sheets = [...$sheets, ...(glob(self::EXT_ROOT . '/Resources/Private/Css/astryx/*.css') ?: [])];
        $sheets = [...$sheets, ...(glob(self::EXT_ROOT . '/ContentBlocks/ContentElements/*/assets/frontend.css') ?: [])];

        $offences = [];
        foreach ($sheets as $sheet) {
            $source = (string)preg_replace('#/\*.*?\*/#s', '', (string)file_get_contents($sheet));
            if (!preg_match_all('#\.(?:astryx|g)-[a-z0-9-]+(?:__[a-z0-9-]+)?(?:\[[^]]*\])*\.([a-zA-Z][a-zA-Z0-9_-]*)#', $source, $matches, PREG_SET_ORDER)) {
                continue;
            }
            foreach ($matches as $match) {
                if (str_starts_with($match[1], 'astryx-') || str_starts_with($match[1], 'g-')) {
                    continue;
                }
                $offences[] = sprintf('%s  %s', self::relative($sheet), $match[0]);
            }
        }

        self::assertSame(
            [],
            array_values(array_unique($offences)),
            "A stylesheet selects a modifier as a class. Astryx removed that shape at v0.6.0:\n"
            . "write `.astryx-x[data-variant=\"flat\"]`, not `.astryx-x.flat`, and render the\n"
            . "attribute from the component rather than the class.\n"
            . implode("\n", array_slice(array_unique($offences), 0, 30)),
        );
    }

    /**
     * How many h1s a fragment emits.
     *
     * Call sites, not branches. A component that can render an h1 writes one
     * `<h1>` per arm of its own `f:if` — PageHeader has two, Heading has two —
     * and counting those counts the ways it could be spelled rather than the
     * heading it renders. What a page emits is one per place it asks for one.
     */
    private static function headingOnesIn(string $file): int
    {
        // A component renders at most one h1 however many branches spell it,
        // and whether it renders one at all is the caller's choice.
        if (str_contains($file, '/Resources/Private/Components/')) {
            return self::alwaysRendersAHeadingOne($file) ? 1 : 0;
        }

        $source = self::withoutComments($file);

        return preg_match_all('#<h1[\s>]#', $source)
            + preg_match_all('#<a:[a-zA-Z.]+[^>]*\bas="h1"#', $source)
            + preg_match_all('#<a:atom\.heading[^>]*\blevel="1"#', $source);
    }

    /**
     * Whether a component renders an h1 no matter how it is called.
     *
     * PageHeader and ErrorMessage do: the h1 is written into their markup and
     * no argument can turn it into anything else. Heading and VisuallyHidden
     * do not — theirs is one case of a switch on `level` or `as`, which the
     * call site chooses and where it is therefore counted.
     */
    private static function alwaysRendersAHeadingOne(string $file): bool
    {
        $source = self::withoutComments($file);
        if (preg_match('#<h1[\s>]#', $source) !== 1) {
            return false;
        }

        return preg_match('#<f:argument\s[^>]*name="(?:level|as)"#', $source) !== 1;
    }

    private static function withoutComments(string $file): string
    {
        return (string)preg_replace(
            '#<f:comment>.*?</f:comment>#s',
            '',
            (string)file_get_contents($file),
        );
    }

    /**
     * Every fragment a page template pulls in, followed one level at a time.
     *
     * A page template names partials with `f:render partial="…"`, a layout
     * with `f:layout`, and components as `<a:layer.name>`; all three can carry
     * an h1 and none is visible to a scan that reads the template alone.
     * PageHeader is exactly that case: the h1 of every content page lives two
     * files away from the template that decides there is one.
     *
     * Components are collected but not descended into. What is asked of a
     * component here is whether it always renders an h1, and what it composes
     * below that is its own business.
     *
     * @return list<string> absolute paths, the template itself first
     */
    private static function pageSources(string $template): array
    {
        $seen = [];
        $queue = [$template];

        while ($queue !== []) {
            $file = array_shift($queue);
            if (isset($seen[$file]) || !is_file($file)) {
                continue;
            }
            $seen[$file] = true;
            if (str_contains($file, '/Resources/Private/Components/')) {
                continue;
            }

            $source = self::withoutComments($file);
            if (preg_match_all('#<f:render\s+partial="([^"]+)"#', $source, $partials)) {
                foreach ($partials[1] as $partial) {
                    $queue[] = self::EXT_ROOT . '/Resources/Private/Templates/Partials/' . $partial . '.fluid.html';
                }
            }
            if (preg_match_all('#<f:layout\s+name="([^"]+)"#', $source, $layouts)) {
                foreach ($layouts[1] as $layout) {
                    $queue[] = self::EXT_ROOT . '/Resources/Private/Templates/Layouts/' . $layout . '.fluid.html';
                }
            }
            if (preg_match_all('#<a:([a-z]+)\.([a-zA-Z][a-zA-Z0-9]*)#', $source, $components, PREG_SET_ORDER)) {
                foreach ($components as $component) {
                    $name = ucfirst($component[2]);
                    $queue[] = sprintf(
                        '%s/Resources/Private/Components/%s/%s/%s.fluid.html',
                        self::EXT_ROOT,
                        ucfirst($component[1]),
                        $name,
                        $name,
                    );
                }
            }
        }

        return array_keys($seen);
    }

    /**
     * One h1 per page. Not "at least one", and not "at most".
     *
     * A document with none has nothing that says what it is; a document with
     * two has two things claiming to, and a screen reader's heading list
     * starts with a disagreement. The lab's end-to-end gate asserts it on a
     * live page, which found the start page emitting both its own
     * screen-reader h1 and a hero element's — this asserts it on the source,
     * so the gate is not the only thing that can catch it.
     */
    #[Test]
    public function everyPageTemplateRendersExactlyOneHeadingOne(): void
    {
        $offences = [];
        $exemptHits = array_fill_keys(array_keys(self::WITHOUT_A_PAGE_HEADING), 0);

        foreach (glob(self::EXT_ROOT . '/Resources/Private/Templates/Pages/*.fluid.html') ?: [] as $template) {
            $name = basename($template, '.fluid.html');
            $found = [];
            foreach (self::pageSources($template) as $file) {
                $count = self::headingOnesIn($file);
                if ($count > 0) {
                    $found[] = sprintf('%s (%d)', self::relative($file), $count);
                }
            }
            $total = array_sum(array_map(
                static fn(string $entry): int => (int)preg_replace('#.*\((\d+)\)$#', '$1', $entry),
                $found,
            ));

            if (array_key_exists($name, self::WITHOUT_A_PAGE_HEADING)) {
                $exemptHits[$name]++;
                if ($total !== 0) {
                    $offences[] = sprintf(
                        '%s is exempt from having an h1 ("%s") but renders %d: %s',
                        $name,
                        self::WITHOUT_A_PAGE_HEADING[$name],
                        $total,
                        implode(', ', $found),
                    );
                }
                continue;
            }

            if ($total !== 1) {
                $offences[] = sprintf(
                    '%s renders %d h1(s)%s',
                    $name,
                    $total,
                    $found === [] ? '' : ': ' . implode(', ', $found),
                );
            }
        }

        self::assertSame(
            [],
            $offences,
            "A page renders exactly one h1: the page template's, saying what the page is.\n"
            . "A content element never renders one — it heads its own band with an h2, and\n"
            . "Atom/Heading's `type` is how a heading is made to LOOK like an h1 without\n"
            . "claiming to be the page's subject.\n"
            . implode("\n", $offences),
        );

        foreach ($exemptHits as $name => $hits) {
            self::assertGreaterThan(
                0,
                $hits,
                sprintf('WITHOUT_A_PAGE_HEADING still names "%s", which is not a page template any more.', $name),
            );
        }
    }

    /**
     * No content element renders an h1, ever.
     *
     * An element is placed on a page that already has one, and it cannot know
     * whether it is the first element or the ninth. Thirty of them rendered
     * `level="1"` because the stylesheet had no way to make an h2 look like an
     * h1 — it has one now, and this is the rule that keeps it used.
     */
    #[Test]
    public function noContentElementRendersAHeadingOne(): void
    {
        $offences = [];
        foreach (glob(self::EXT_ROOT . '/ContentBlocks/ContentElements/*/templates/frontend.html') ?: [] as $file) {
            $count = self::headingOnesIn($file);
            if ($count > 0) {
                $offences[] = sprintf('%s renders %d h1(s)', self::relative($file), $count);
            }
        }

        self::assertSame(
            [],
            $offences,
            "A content element heads its own band with an h2. To make one look like an h1,\n"
            . "pass Atom/Heading a size instead of a level: level=\"2\" type=\"heading-1\".\n"
            . implode("\n", $offences),
        );
    }
}
